### ISSUE TITLE
Brand Image

### ISSUE THREAD

**Issue by damo-da** [ServerChef/serverchef.github.io#6]
Shouldn't we convert the current brand text, from "ServerChef" to the logo? 
![https://puu.sh/uaEBF/38d82af965.png](https://puu.sh/uaEBF/38d82af965.png)

**Comment by XusBadia** [comment]
Fixed.

**Comment by damo-da** [comment]
Awesome! Could you close the issue from next time?

**Comment by damo-da** [comment]
I think the brand image is not resized. This is what I get: ![https://puu.sh/uaIhJ/9cfe859e79.png](https://puu.sh/uaIhJ/9cfe859e79.png)

**Comment by XusBadia** [comment]
Sure, I'll close it next time!

If you "shift+reload" it should fix the image. I guess the CSS is in cache, and that fixed it for me.

**Comment by damo-da** [comment]
Yup! It's fixed!
